### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by cameronroe** [MoOx/metalsmith-rss#2]
It's trying to read a collection or something. When I add this line above the collection.length check, it suppresses the error.

```
if (!metadata.collections[collection]) {
  return done();
}
```

**Comment by bradhowes** [comment]
Per the README, the default value for the `collection` key is "posts". If you use something else as the collection key (such as "articles" like I do), then you need to supply that in the options:

```
.use(rss({
  feedOptions: {
    site_url: ...,
    title: ...
  },
  collection: "articles",
  limit: 50
}))
```
